services:
  ollama:
    build:
      context: ./docker/ollama/
    container_name: verse-ollama
    ports:
      - 7869:11434
    networks:
      - verse-network
    healthcheck:
      test: ["CMD-SHELL", "command ollama"]
      interval: 5s
      retries: 3

networks:
  verse-network:
    external: false
