services:
  ollama:
    build:
      context: ./docker/ollama/
    container_name: ollama
    ports:
      - 7869:11434
    networks:
      - verse-network
    volumes:
      - ./volumes/ollama:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "command ollama"]
      interval: 5s
      retries: 3

networks:
  verse-network:
    external: false
